---
name: ci-calculator-project-workflow
on:
  pull_request:
    branches: [development]  # eventos de pull request na branch development somente
jobs:
  check-application:  # nome do job
    runs-on: ubuntu-latest  # imagem da action
    steps:
      - uses: actions/checkout@v4  # action pronta de github.com/actions
      - uses: actions/setup-node@v4  # action pronta de github.com/actions
        with:
          node-version: 21.2.0
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mathstylishdev/calculator-project-ci-example:1.0
      - run: npm install
      - run: npm test
      - run: npm start
