---
name: ci-calculator-project-workflow
on:
  pull_request:
    branches: [development]  # eventos de pull request na branch development somente
jobs:
  check-application:  # nome do job
    runs-on: ubuntu-latest  # imagem da action
    strategy:
      matrix:
        node: [18.12.0, 19.3.0, 21.2.0]
    steps:
      - uses: actions/checkout@v4  # action pronta de github.com/actions
      - uses: actions/setup-node@v4  # action pronta de github.com/actions
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm test
      - run: npm start
