---
name: ci-calculator-project-workflow
on:
  pull_request:
    branches: [development]  # eventos de pull request na branch development somente
jobs:
  check-application:  # nome do job
    runs-on: ubuntu-latest  # imagem da action
    steps:
      - uses: actions/checkout@v4  # action pronta de github.com/actions
      - uses: actions/setup-node@v4  # action pronta de github.com/actions
        with:
          node-version: 18.12.0
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm test
      - run: npm start
